# Generated by Django 5.0.3 on 2024-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
